name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *" # 毎日深夜に自動実行
  workflow_dispatch: # 手動でいつでも実行できるボタン

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
